<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="145237" started-at="2018-05-20T08:20:38Z" finished-at="2018-05-20T08:23:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="145237" started-at="2018-05-20T08:20:38Z" finished-at="2018-05-20T08:23:03Z">
      <class name="com.qa.crm.testcases.HomepageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.crm.testcases.HomepageTest@724af044]" name="setUp" is-config="true" duration-ms="144941" started-at="2018-05-20T13:50:38Z" finished-at="2018-05-20T13:53:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyLoginUserNameTest()[pri:0, instance:com.qa.crm.testcases.HomepageTest@724af044]" name="verifyLoginUserNameTest" duration-ms="223" started-at="2018-05-20T13:53:03Z" finished-at="2018-05-20T13:53:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[wrong Username expected [Pritesh Khambekar] but found [  User: Pritesh Khambekar]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: wrong Username expected [Pritesh Khambekar] but found [  User: Pritesh Khambekar]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.qa.crm.testcases.HomepageTest.verifyLoginUserNameTest(HomepageTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginUserNameTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.crm.testcases.HomepageTest@724af044]" name="tearDown" is-config="true" duration-ms="55" started-at="2018-05-20T13:53:03Z" finished-at="2018-05-20T13:53:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.crm.testcases.HomepageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
